name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
